//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Data.Objects.DataClasses;


namespace AppGest.Datos.Persistencia
{
    
    public partial class Reg_encab
    {
    
    
        #region Métodos de Copia
    
        public virtual void CopiarDesde(EntityObject origen)
        {
    
            var entidad = (Reg_encab) origen;
            
    		Id = entidad.Id;
    		FechaAlta = entidad.FechaAlta;
    		FechaRegistro = entidad.FechaRegistro;
    		Comentario = entidad.Comentario;
    		FechaModif = entidad.FechaModif;
    		FechaBaja = entidad.FechaBaja;
    		Identificador = entidad.Identificador;
    		Tipo = entidad.Tipo;
        }
    
        public virtual void CopiarA(EntityObject destino)
        {
    
            var entidad = (Reg_encab) destino;
            
    		 entidad.Id = Id;
    		 entidad.FechaAlta = FechaAlta;
    		 entidad.FechaRegistro = FechaRegistro;
    		 entidad.Comentario = Comentario;
    		 entidad.FechaModif = FechaModif;
    		 entidad.FechaBaja = FechaBaja;
    		 entidad.Identificador = Identificador;
    		 entidad.Tipo = Tipo;
        }

        #endregion
    
    }
}
