//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Data.Objects.DataClasses;


namespace AppGest.Datos.Persistencia
{
    
    public partial class Usuario : Entidad
    {
    
        #region Composiciones
    

        #endregion
    
        #region Agregaciones
    
        /// <summary>
        /// Establece el objeto asociado a la propiedad 'Persona' de esta instancia, teniendo en cuena
        /// si se se debe hacer por instancia (propiedad 'Persona') o por referencia (propiedad 'PersonaReference').
        /// </summary>
        /// <param name="nuevo">Entidad a asociar</param>
        /// <param name="forzarPorInstancia">(Opcional) Fuerza el seteo por referencia.</param>
        public virtual void SetPersona(Persona nuevo, bool forzarPorInstancia = false)
        {
            this.SetRelacion("Persona", "PersonaReference", nuevo, forzarPorInstancia);
        }
    

        #endregion
    
    }
}
