//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Data.Objects.DataClasses;
using System.Linq;


namespace AppGest.Datos.Persistencia
{
    public partial class Cliente : Persona
    {
    
        public const string PROP_NROCLIENTE = "NroCliente";
        public const string PROP_CUIT = "CUIT";
        public const string PROP_DOMICILIOFISCAL = "DomicilioFiscal";
        public const string PROP_RAZONSOCIAL = "RazonSocial";
    
        protected override IList<string> ObtenerPropiedadesEntidad()
        {
            return new List<string>() {
                "NroCliente"
              , "CUIT"
              , "DomicilioFiscal"
              , "RazonSocial"
              }.Union(base.ObtenerPropiedadesEntidad()).ToList();
        }
    }
    
    
    public partial class Cochera : Entidad
    {
    
    
        protected override IList<string> ObtenerPropiedadesEntidad()
        {
            return new List<string>() {
                }.Union(base.ObtenerPropiedadesEntidad()).ToList();
        }
    }
    
    
    public partial class Concepto : EB
    {
    
        public const string PROP_CLASE = "Clase";
        public const string PROP_VALOR = "Valor";
        public const string PROP_DESISTEMA = "DeSistema";
    
        protected override IList<string> ObtenerPropiedadesEntidad()
        {
            return new List<string>() {
                "Clase"
              , "Valor"
              , "DeSistema"
              }.Union(base.ObtenerPropiedadesEntidad()).ToList();
        }
    }
    
    
    public partial class ConfMenu
    {
    
        public const string PROP_ID = "Id";
        public const string PROP_ORDEN = "Orden";
        public const string PROP_PAGINAS = "Paginas";
        public const string PROP_GRUPOS = "Grupos";
        public const string PROP_ITEMS = "Items";
        public const string PROP_IMAGENITEM = "ImagenItem";
        public const string PROP_TAGITEM = "TagItem";
        public const string PROP_TOOLTIPS = "ToolTips";
        public const string PROP_AUTOSIZE = "AutoSize";
    
        protected virtual IList<string> ObtenerPropiedadesEntidad()
        {
            return new List<string>() {
                "Id"
              , "Orden"
              , "Paginas"
              , "Grupos"
              , "Items"
              , "ImagenItem"
              , "TagItem"
              , "ToolTips"
              , "AutoSize"
              };
        }
    }
    
    
    public partial class EB
    {
    
        public const string PROP_ID = "Id";
        public const string PROP_NOMBRE = "Nombre";
        public const string PROP_ALTA = "Alta";
        public const string PROP_BAJA = "Baja";
        public const string PROP_ABREVIATURA = "Abreviatura";
        public const string PROP_DESCRIPCION = "Descripcion";
        public const string PROP_OBSERVACIONES = "Observaciones";
    
        protected virtual IList<string> ObtenerPropiedadesEntidad()
        {
            return new List<string>() {
                "Id"
              , "Nombre"
              , "Alta"
              , "Baja"
              , "Abreviatura"
              , "Descripcion"
              , "Observaciones"
              };
        }
    }
    
    
    public partial class Empleado : Persona
    {
    
        public const string PROP_CUIL = "CUIL";
    
        protected override IList<string> ObtenerPropiedadesEntidad()
        {
            return new List<string>() {
                "CUIL"
              }.Union(base.ObtenerPropiedadesEntidad()).ToList();
        }
    }
    
    
    public partial class Empresa : Persona
    {
    
    
        protected override IList<string> ObtenerPropiedadesEntidad()
        {
            return new List<string>() {
                }.Union(base.ObtenerPropiedadesEntidad()).ToList();
        }
    }
    
    
    public partial class Entidad : EB
    {
    
    
        protected override IList<string> ObtenerPropiedadesEntidad()
        {
            return new List<string>() {
                }.Union(base.ObtenerPropiedadesEntidad()).ToList();
        }
    }
    
    
    public partial class Persona : Entidad
    {
    
        public const string PROP_TIPO = "Tipo";
        public const string PROP_CONTACTO = "Contacto";
        public const string PROP_NOMBRE2 = "Nombre2";
        public const string PROP_APELLIDO = "Apellido";
        public const string PROP_DNI = "Dni";
        public const string PROP_LOCK = "Lock";
    
        protected override IList<string> ObtenerPropiedadesEntidad()
        {
            return new List<string>() {
                "Tipo"
              , "Contacto"
              , "Nombre2"
              , "Apellido"
              , "Dni"
              , "Lock"
              }.Union(base.ObtenerPropiedadesEntidad()).ToList();
        }
    }
    
    
    public partial class Reg_Det
    {
    
        public const string PROP_ID = "Id";
        public const string PROP_FECHAALTA = "FechaAlta";
        public const string PROP_FECHABAJA = "FechaBaja";
        public const string PROP_FECHAMODIF = "FechaModif";
        public const string PROP_CANTIDAD = "Cantidad";
        public const string PROP_PRECIO = "Precio";
        public const string PROP_IMPORTE = "Importe";
        public const string PROP_VALNUM1 = "ValNum1";
        public const string PROP_VALNUM2 = "ValNum2";
        public const string PROP_VALNUM3 = "ValNum3";
        public const string PROP_VALNUM4 = "ValNum4";
        public const string PROP_VALTEXT1 = "ValText1";
        public const string PROP_VALTEXT2 = "ValText2";
        public const string PROP_VALTEXT3 = "ValText3";
        public const string PROP_VALTEXT4 = "ValText4";
        public const string PROP_COMENTARIO = "Comentario";
        public const string PROP_VALFECHA1 = "ValFecha1";
        public const string PROP_VALFECHA2 = "ValFecha2";
        public const string PROP_VALFECHA3 = "ValFecha3";
        public const string PROP_VALFECHA4 = "ValFecha4";
    
        protected virtual IList<string> ObtenerPropiedadesEntidad()
        {
            return new List<string>() {
                "Id"
              , "FechaAlta"
              , "FechaBaja"
              , "FechaModif"
              , "Cantidad"
              , "Precio"
              , "Importe"
              , "ValNum1"
              , "ValNum2"
              , "ValNum3"
              , "ValNum4"
              , "ValText1"
              , "ValText2"
              , "ValText3"
              , "ValText4"
              , "Comentario"
              , "ValFecha1"
              , "ValFecha2"
              , "ValFecha3"
              , "ValFecha4"
              };
        }
    }
    
    
    public partial class Reg_encab
    {
    
        public const string PROP_ID = "Id";
        public const string PROP_FECHAALTA = "FechaAlta";
        public const string PROP_FECHAREGISTRO = "FechaRegistro";
        public const string PROP_COMENTARIO = "Comentario";
        public const string PROP_FECHAMODIF = "FechaModif";
        public const string PROP_FECHABAJA = "FechaBaja";
        public const string PROP_IDENTIFICADOR = "Identificador";
        public const string PROP_TIPO = "Tipo";
    
        protected virtual IList<string> ObtenerPropiedadesEntidad()
        {
            return new List<string>() {
                "Id"
              , "FechaAlta"
              , "FechaRegistro"
              , "Comentario"
              , "FechaModif"
              , "FechaBaja"
              , "Identificador"
              , "Tipo"
              };
        }
    }
    
    
    public partial class Usuario : Entidad
    {
    
        public const string PROP_CLAVE = "Clave";
        public const string PROP_TIPO = "Tipo";
    
        protected override IList<string> ObtenerPropiedadesEntidad()
        {
            return new List<string>() {
                "Clave"
              , "Tipo"
              }.Union(base.ObtenerPropiedadesEntidad()).ToList();
        }
    }
    
    
    public partial class Vehiculo : Entidad
    {
    
        public const string PROP_MODELO = "Modelo";
        public const string PROP_MARCA = "Marca";
    
        protected override IList<string> ObtenerPropiedadesEntidad()
        {
            return new List<string>() {
                "Modelo"
              , "Marca"
              }.Union(base.ObtenerPropiedadesEntidad()).ToList();
        }
    }
    
    
}


