//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Data.Objects.DataClasses;


namespace AppGest.Datos.Persistencia
{
    
    public partial class Persona
    {
    
    
        #region Métodos de Copia
    
        public override void CopiarDesde(EntityObject origen)
        {
            base.CopiarDesde(origen);
    
            var entidad = (Persona) origen;
            
    		Tipo = entidad.Tipo;
    		Contacto.CopiarDesde(entidad.Contacto);
    		Nombre2 = entidad.Nombre2;
    		Apellido = entidad.Apellido;
    		Dni = entidad.Dni;
    		Lock = entidad.Lock;
        }
    
        public override void CopiarA(EntityObject destino)
        {
            base.CopiarA(destino);
    
            var entidad = (Persona) destino;
            
    		 entidad.Tipo = Tipo;
    		 entidad.Contacto.CopiarDesde(Contacto);
    		 entidad.Nombre2 = Nombre2;
    		 entidad.Apellido = Apellido;
    		 entidad.Dni = Dni;
    		 entidad.Lock = Lock;
        }

        #endregion
    
    }
}
