//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Data.Objects.DataClasses;


namespace AppGest.Datos.Persistencia
{
    
    public partial class Reg_Det
    {
    
    
        #region Métodos de Copia
    
        public virtual void CopiarDesde(EntityObject origen)
        {
    
            var entidad = (Reg_Det) origen;
            
    		Id = entidad.Id;
    		FechaAlta = entidad.FechaAlta;
    		FechaBaja = entidad.FechaBaja;
    		FechaModif = entidad.FechaModif;
    		Cantidad = entidad.Cantidad;
    		Precio = entidad.Precio;
    		Importe = entidad.Importe;
    		ValNum1 = entidad.ValNum1;
    		ValNum2 = entidad.ValNum2;
    		ValNum3 = entidad.ValNum3;
    		ValNum4 = entidad.ValNum4;
    		ValText1 = entidad.ValText1;
    		ValText2 = entidad.ValText2;
    		ValText3 = entidad.ValText3;
    		ValText4 = entidad.ValText4;
    		Comentario = entidad.Comentario;
    		ValFecha1 = entidad.ValFecha1;
    		ValFecha2 = entidad.ValFecha2;
    		ValFecha3 = entidad.ValFecha3;
    		ValFecha4 = entidad.ValFecha4;
        }
    
        public virtual void CopiarA(EntityObject destino)
        {
    
            var entidad = (Reg_Det) destino;
            
    		 entidad.Id = Id;
    		 entidad.FechaAlta = FechaAlta;
    		 entidad.FechaBaja = FechaBaja;
    		 entidad.FechaModif = FechaModif;
    		 entidad.Cantidad = Cantidad;
    		 entidad.Precio = Precio;
    		 entidad.Importe = Importe;
    		 entidad.ValNum1 = ValNum1;
    		 entidad.ValNum2 = ValNum2;
    		 entidad.ValNum3 = ValNum3;
    		 entidad.ValNum4 = ValNum4;
    		 entidad.ValText1 = ValText1;
    		 entidad.ValText2 = ValText2;
    		 entidad.ValText3 = ValText3;
    		 entidad.ValText4 = ValText4;
    		 entidad.Comentario = Comentario;
    		 entidad.ValFecha1 = ValFecha1;
    		 entidad.ValFecha2 = ValFecha2;
    		 entidad.ValFecha3 = ValFecha3;
    		 entidad.ValFecha4 = ValFecha4;
        }

        #endregion
    
    }
}
