//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Data.Objects.DataClasses;


namespace AppGest.Datos.Persistencia
{
    
    public partial class EB
    {
    
    
        #region Métodos de Copia
    
        public virtual void CopiarDesde(EntityObject origen)
        {
    
            var entidad = (EB) origen;
            
    		Id = entidad.Id;
    		Nombre = entidad.Nombre;
    		Alta = entidad.Alta;
    		Baja = entidad.Baja;
    		Abreviatura = entidad.Abreviatura;
    		Descripcion = entidad.Descripcion;
    		Observaciones = entidad.Observaciones;
        }
    
        public virtual void CopiarA(EntityObject destino)
        {
    
            var entidad = (EB) destino;
            
    		 entidad.Id = Id;
    		 entidad.Nombre = Nombre;
    		 entidad.Alta = Alta;
    		 entidad.Baja = Baja;
    		 entidad.Abreviatura = Abreviatura;
    		 entidad.Descripcion = Descripcion;
    		 entidad.Observaciones = Observaciones;
        }

        #endregion
    
    }
}
