//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Data.Objects.DataClasses;


namespace AppGest.Datos.Persistencia
{
    
    public partial class ConfMenu
    {
    
    
        #region Métodos de Copia
    
        public virtual void CopiarDesde(EntityObject origen)
        {
    
            var entidad = (ConfMenu) origen;
            
    		Id = entidad.Id;
    		Orden = entidad.Orden;
    		Paginas = entidad.Paginas;
    		Grupos = entidad.Grupos;
    		Items = entidad.Items;
    		ImagenItem = entidad.ImagenItem;
    		TagItem = entidad.TagItem;
    		ToolTips = entidad.ToolTips;
    		AutoSize = entidad.AutoSize;
        }
    
        public virtual void CopiarA(EntityObject destino)
        {
    
            var entidad = (ConfMenu) destino;
            
    		 entidad.Id = Id;
    		 entidad.Orden = Orden;
    		 entidad.Paginas = Paginas;
    		 entidad.Grupos = Grupos;
    		 entidad.Items = Items;
    		 entidad.ImagenItem = ImagenItem;
    		 entidad.TagItem = TagItem;
    		 entidad.ToolTips = ToolTips;
    		 entidad.AutoSize = AutoSize;
        }

        #endregion
    
    }
}
