//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Data.Objects.DataClasses;


namespace AppGest.Datos.Persistencia
{
    
    public partial class Contacto
    {
    
    
        #region Métodos de Copia
    
        public virtual void CopiarDesde(Contacto origen)
        {
    
            var entidad = (Contacto) origen;
            
    		Domicilio = entidad.Domicilio;
    		Telefono = entidad.Telefono;
    		TelefonoTrabajo = entidad.TelefonoTrabajo;
    		Movil = entidad.Movil;
    		Email = entidad.Email;
        }
    
        public virtual void CopiarA(Contacto destino)
        {
    
            var entidad = (Contacto) destino;
            
    		 entidad.Domicilio = Domicilio;
    		 entidad.Telefono = Telefono;
    		 entidad.TelefonoTrabajo = TelefonoTrabajo;
    		 entidad.Movil = Movil;
    		 entidad.Email = Email;
        }

        #endregion
    
    }
}
