//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Data.Objects.DataClasses;


namespace AppGest.Datos.Persistencia
{
    
    public partial class Concepto
    {
    
    
        #region Métodos de Copia
    
        public override void CopiarDesde(EntityObject origen)
        {
            base.CopiarDesde(origen);
    
            var entidad = (Concepto) origen;
            
    		Clase = entidad.Clase;
    		Valor = entidad.Valor;
    		DeSistema = entidad.DeSistema;
        }
    
        public override void CopiarA(EntityObject destino)
        {
            base.CopiarA(destino);
    
            var entidad = (Concepto) destino;
            
    		 entidad.Clase = Clase;
    		 entidad.Valor = Valor;
    		 entidad.DeSistema = DeSistema;
        }

        #endregion
    
    }
}
